const REACT_APP_AUTH0_DOMAIN = "dev-2g4fvge2.us.auth0.com";
const REACT_APP_AUTH0_CLIENT_ID = "z9vdxCYwo6YeytS70LZwsPQ1YyFXLyAC";

export {
    REACT_APP_AUTH0_DOMAIN,
    REACT_APP_AUTH0_CLIENT_ID,
}